import type { ImageData } from "./types.ts";

// Картинки лежат в public/images/posts/<ID>/<file>
// BASE_URL = "/" в dev, "/kinotoaster/" на GH Pages (значение берётся из vite.config.ts)
const asset = (p: string) => {
	const base = import.meta.env.BASE_URL;
	return `${base}${p.replace(/^\/+/, '')}`;
};

export const IMAGES: ImageData[] = [
	{
		id: 'SKAZKA-O-TARE-SALTANE',
		title: 'Сказка о царе Салтане',
		src: asset('images/posts/SKAZKA-O-TARE-SALTANE/src.png'),
		'data-high-res': asset('images/posts/SKAZKA-O-TARE-SALTANE/data-high-res.png'),
		'data-4x': asset('images/posts/SKAZKA-O-TARE-SALTANE/data-4x.png'),
		fullScreen: asset('images/posts/SKAZKA-O-TARE-SALTANE/fullscreen.jpg'),
	},
	{
		id: 'AVGUST',
		title: 'АВГУСТ',
		src: asset('images/posts/AVGUST/src.jpg'),
		'data-high-res': asset('images/posts/AVGUST/data-high-res.jpg'),
		'data-4x': asset('images/posts/AVGUST/data-4x.jpg'),
		fullScreen: asset('images/posts/AVGUST/fullscreen.jpg'),
	},
	{
		id: 'V-SPISKAK-NE-ZNACILSY',
		title: 'В списках не значился',
		src: asset('images/posts/V-SPISKAK-NE-ZNACILSY/src.jpg'),
		'data-high-res': asset('images/posts/V-SPISKAK-NE-ZNACILSY/data-high-res.jpg'),
		'data-4x': asset('images/posts/V-SPISKAK-NE-ZNACILSY/data-4x.jpg'),
		fullScreen: asset('images/posts/V-SPISKAK-NE-ZNACILSY/fullscreen.jpg'),
	},
	{
		id: 'AVGUST-TIZER',
		title: 'АВГУСТ ТИЗЕР',
		src: asset('images/posts/AVGUST-TIZER/src.jpg'),
		'data-high-res': asset('images/posts/AVGUST-TIZER/data-high-res.jpg'),
		'data-4x': asset('images/posts/AVGUST-TIZER/data-4x.jpg'),
		fullScreen: asset('images/posts/AVGUST-TIZER/fullscreen.jpg'),
	},
	{
		id: 'PERVYI-NA-OLIMPE',
		title: 'ПЕРВЫЙ НА ОЛИМПЕ',
		src: asset('images/posts/PERVYI-NA-OLIMPE/src.jpg'),
		'data-high-res': asset('images/posts/PERVYI-NA-OLIMPE/data-high-res.jpg'),
		'data-4x': asset('images/posts/PERVYI-NA-OLIMPE/data-4x.jpg'),
		fullScreen: asset('images/posts/PERVYI-NA-OLIMPE/fullscreen.jpg'),
	},
	{
		id: 'AVGUST-TIZER-2',
		title: 'АВГУСТ ТИЗЕР 2',
		src: asset('images/posts/AVGUST-TIZER-2/src.jpg'),
		'data-high-res': asset('images/posts/AVGUST-TIZER-2/data-high-res.jpg'),
		'data-4x': asset('images/posts/AVGUST-TIZER-2/data-4x.jpg'),
		fullScreen: asset('images/posts/AVGUST-TIZER-2/fullscreen.jpg'),
	},
	{
		id: 'KRAKEN-1',
		title: 'Кракен',
		src: asset('images/posts/KRAKEN-1/src.jpg'),
		'data-high-res': asset('images/posts/KRAKEN-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/KRAKEN-1/data-4x.jpg'),
		fullScreen: asset('images/posts/KRAKEN-1/fullscreen.jpg'),
	},
	{
		id: 'KRAKEN',
		title: 'Кракен',
		src: asset('images/posts/KRAKEN/src.jpg'),
		'data-high-res': asset('images/posts/KRAKEN/data-high-res.jpg'),
		'data-4x': asset('images/posts/KRAKEN/data-4x.jpg'),
		fullScreen: asset('images/posts/KRAKEN/fullscreen.jpg'),
	},
	{
		id: 'LYBOV-SOVETSKOGO-SOYZA',
		title: 'Любовь Советского Союза',
		src: asset('images/posts/LYBOV-SOVETSKOGO-SOYZA/src.jpg'),
		'data-high-res': asset('images/posts/LYBOV-SOVETSKOGO-SOYZA/data-high-res.jpg'),
		'data-4x': asset('images/posts/LYBOV-SOVETSKOGO-SOYZA/data-4x.jpg'),
		fullScreen: asset('images/posts/LYBOV-SOVETSKOGO-SOYZA/fullscreen.jpg'),
	},
	{
		id: 'ZLOI-GOROD-MEZDUNARODNYI-POSTER',
		title: 'Злой город (международный постер)',
		src: asset('images/posts/ZLOI-GOROD-MEZDUNARODNYI-POSTER/src.jpg'),
		'data-high-res': asset('images/posts/ZLOI-GOROD-MEZDUNARODNYI-POSTER/data-high-res.jpg'),
		'data-4x': asset('images/posts/ZLOI-GOROD-MEZDUNARODNYI-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/ZLOI-GOROD-MEZDUNARODNYI-POSTER/fullscreen.jpg'),
	},
	{
		id: 'KOROV-EV',
		title: 'КОРОВЬЕВ',
		src: asset('images/posts/KOROV-EV/src.jpg'),
		'data-high-res': asset('images/posts/KOROV-EV/data-high-res.jpg'),
		'data-4x': asset('images/posts/KOROV-EV/data-4x.jpg'),
		fullScreen: asset('images/posts/KOROV-EV/fullscreen.jpg'),
	},
	{
		id: 'CELYSKIN-PERVYE',
		title: 'Челюскин. Первые',
		src: asset('images/posts/CELYSKIN-PERVYE/src.jpg'),
		'data-high-res': asset('images/posts/CELYSKIN-PERVYE/data-high-res.jpg'),
		'data-4x': asset('images/posts/CELYSKIN-PERVYE/data-4x.jpg'),
		fullScreen: asset('images/posts/CELYSKIN-PERVYE/fullscreen.jpg'),
	},
	{
		id: 'GDR',
		title: 'ГДР',
		src: asset('images/posts/GDR/src.jpg'),
		'data-high-res': asset('images/posts/GDR/data-high-res.jpg'),
		'data-4x': asset('images/posts/GDR/data-4x.jpg'),
		fullScreen: asset('images/posts/GDR/fullscreen.jpg'),
	},
	{
		id: 'CISTYE',
		title: 'ЧИСТЫЕ',
		src: asset('images/posts/CISTYE/src.jpg'),
		'data-high-res': asset('images/posts/CISTYE/data-high-res.jpg'),
		'data-4x': asset('images/posts/CISTYE/data-4x.jpg'),
		fullScreen: asset('images/posts/CISTYE/fullscreen.jpg'),
	},
	{
		id: 'VOLAND-1',
		title: 'ВОЛАНД',
		src: asset('images/posts/VOLAND-1/src.jpg'),
		'data-high-res': asset('images/posts/VOLAND-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/VOLAND-1/data-4x.jpg'),
		fullScreen: asset('images/posts/VOLAND-1/fullscreen.jpg'),
	},
	{
		id: 'MASTER-I-MARGARITA',
		title: 'МАСТЕР и МАРГАРИТА',
		src: asset('images/posts/MASTER-I-MARGARITA/src.jpg'),
		'data-high-res': asset('images/posts/MASTER-I-MARGARITA/data-high-res.jpg'),
		'data-4x': asset('images/posts/MASTER-I-MARGARITA/data-4x.jpg'),
		fullScreen: asset('images/posts/MASTER-I-MARGARITA/fullscreen.jpg'),
	},
	{
		id: 'MARGARITA',
		title: 'МАРГАРИТА',
		src: asset('images/posts/MARGARITA/src.jpg'),
		'data-high-res': asset('images/posts/MARGARITA/data-high-res.jpg'),
		'data-4x': asset('images/posts/MARGARITA/data-4x.jpg'),
		fullScreen: asset('images/posts/MARGARITA/fullscreen.jpg'),
	},
	{
		id: 'PROSTOKVASINO',
		title: 'Простоквашино',
		src: asset('images/posts/PROSTOKVASINO/src.jpg'),
		'data-high-res': asset('images/posts/PROSTOKVASINO/data-high-res.jpg'),
		'data-4x': asset('images/posts/PROSTOKVASINO/data-4x.jpg'),
		fullScreen: asset('images/posts/PROSTOKVASINO/fullscreen.jpg'),
	},
	{
		id: 'BURATINO-1',
		title: 'Буратино',
		src: asset('images/posts/BURATINO-1/src.jpg'),
		'data-high-res': asset('images/posts/BURATINO-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/BURATINO-1/data-4x.jpg'),
		fullScreen: asset('images/posts/BURATINO-1/fullscreen.jpg'),
	},
	{
		id: 'FINNIK-2',
		title: 'ФИННИК 2',
		src: asset('images/posts/FINNIK-2/src.jpg'),
		'data-high-res': asset('images/posts/FINNIK-2/data-high-res.jpg'),
		'data-4x': asset('images/posts/FINNIK-2/data-4x.jpg'),
		fullScreen: asset('images/posts/FINNIK-2/fullscreen.jpg'),
	},
	{
		id: 'LYBOPYTNAY-VARVARA-2',
		title: 'Любопытная Варвара 2',
		src: asset('images/posts/LYBOPYTNAY-VARVARA-2/src.jpg'),
		'data-high-res': asset('images/posts/LYBOPYTNAY-VARVARA-2/data-high-res.jpg'),
		'data-4x': asset('images/posts/LYBOPYTNAY-VARVARA-2/data-4x.jpg'),
		fullScreen: asset('images/posts/LYBOPYTNAY-VARVARA-2/fullscreen.jpg'),
	},
	{
		id: 'CEBURASKA-2-TIZER',
		title: 'ЧЕБУРАШКА 2 ТИЗЕР',
		src: asset('images/posts/CEBURASKA-2-TIZER/src.jpg'),
		'data-high-res': asset('images/posts/CEBURASKA-2-TIZER/data-high-res.jpg'),
		'data-4x': asset('images/posts/CEBURASKA-2-TIZER/data-4x.jpg'),
		fullScreen: asset('images/posts/CEBURASKA-2-TIZER/fullscreen.jpg'),
	},
	{
		id: 'CUK-I-GEK-BOL-SOE-PRI',
		title: 'Чук и Гек: большое при',
		src: asset('images/posts/CUK-I-GEK-BOL-SOE-PRI/src.jpg'),
		'data-high-res': asset('images/posts/CUK-I-GEK-BOL-SOE-PRI/data-high-res.jpg'),
		'data-4x': asset('images/posts/CUK-I-GEK-BOL-SOE-PRI/data-4x.jpg'),
		fullScreen: asset('images/posts/CUK-I-GEK-BOL-SOE-PRI/fullscreen.jpg'),
	},
	{
		id: 'FINIST-PERVYI-BOGATYR',
		title: 'Финист: Первый богатырь',
		src: asset('images/posts/FINIST-PERVYI-BOGATYR/src.jpg'),
		'data-high-res': asset('images/posts/FINIST-PERVYI-BOGATYR/data-high-res.jpg'),
		'data-4x': asset('images/posts/FINIST-PERVYI-BOGATYR/data-4x.jpg'),
		fullScreen: asset('images/posts/FINIST-PERVYI-BOGATYR/fullscreen.jpg'),
	},
	{
		id: 'CELYSKIN-PERSONAZNYI-POSTER',
		title: 'Челюскин. Персонажный постер',
		src: asset('images/posts/CELYSKIN-PERSONAZNYI-POSTER/src.jpg'),
		'data-high-res': asset('images/posts/CELYSKIN-PERSONAZNYI-POSTER/data-high-res.jpg'),
		'data-4x': asset('images/posts/CELYSKIN-PERSONAZNYI-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/CELYSKIN-PERSONAZNYI-POSTER/fullscreen.jpg'),
	},
	{
		id: 'DOMOVENOK-KUZY',
		title: 'Домовёнок Кузя',
		src: asset('images/posts/DOMOVENOK-KUZY/src.jpg'),
		'data-high-res': asset('images/posts/DOMOVENOK-KUZY/data-high-res.jpg'),
		'data-4x': asset('images/posts/DOMOVENOK-KUZY/data-4x.jpg'),
		fullScreen: asset('images/posts/DOMOVENOK-KUZY/fullscreen.jpg'),
	},
	{
		id: 'VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA',
		title: 'Волшебник Изумрудного города. Дорога из желтого кирпича',
		src: asset('images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA/src.jpg'),
		'data-high-res': asset(
			'images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA/data-high-res.jpg'
		),
		'data-4x': asset(
			'images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA/data-4x.jpg'
		),
		fullScreen: asset(
			'images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA/fullscreen.jpg'
		),
	},
	{
		id: 'VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA-1',
		title: 'Волшебник Изумрудного города. Дорога из желтого кирпича',
		src: asset('images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA-1/src.jpg'),
		'data-high-res': asset(
			'images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA-1/data-high-res.jpg'
		),
		'data-4x': asset(
			'images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA-1/data-4x.jpg'
		),
		fullScreen: asset(
			'images/posts/VOLSEBNIK-IZUMRUDNOGO-GORODA-DOROGA-IZ-ZELTOGO-KIRPICA-1/fullscreen.jpg'
		),
	},
	{
		id: 'SEREBRYNYE-KON-KI',
		title: 'СЕРЕБРЯНЫЕ КОНЬКИ',
		src: asset('images/posts/SEREBRYNYE-KON-KI/src.jpeg'),
		'data-high-res': asset('images/posts/SEREBRYNYE-KON-KI/data-high-res.jpeg'),
		'data-4x': asset('images/posts/SEREBRYNYE-KON-KI/data-4x.jpeg'),
		fullScreen: asset('images/posts/SEREBRYNYE-KON-KI/fullscreen.jpeg'),
	},
	{
		id: 'POVELITEL-VETRA',
		title: 'ПОВЕЛИТЕЛЬ ВЕТРА',
		src: asset('images/posts/POVELITEL-VETRA/src.jpg'),
		'data-high-res': asset('images/posts/POVELITEL-VETRA/data-high-res.jpg'),
		'data-4x': asset('images/posts/POVELITEL-VETRA/data-4x.jpg'),
		fullScreen: asset('images/posts/POVELITEL-VETRA/fullscreen.jpg'),
	},
	{
		id: 'TERBER',
		title: 'Цербер',
		src: asset('images/posts/TERBER/src.jpg'),
		'data-high-res': asset('images/posts/TERBER/data-high-res.jpg'),
		'data-4x': asset('images/posts/TERBER/data-4x.jpg'),
		fullScreen: asset('images/posts/TERBER/fullscreen.jpg'),
	},
	{
		id: 'DOPOLNITEL-NYI-UROK',
		title: 'Дополнительный урок',
		src: asset('images/posts/DOPOLNITEL-NYI-UROK/src.jpg'),
		'data-high-res': asset('images/posts/DOPOLNITEL-NYI-UROK/data-high-res.jpg'),
		'data-4x': asset('images/posts/DOPOLNITEL-NYI-UROK/data-4x.jpg'),
		fullScreen: asset('images/posts/DOPOLNITEL-NYI-UROK/fullscreen.jpg'),
	},
	{
		id: 'IMPERATRITY',
		title: 'ИМПЕРАТРИЦЫ',
		src: asset('images/posts/IMPERATRITY/src.jpg'),
		'data-high-res': asset('images/posts/IMPERATRITY/data-high-res.jpg'),
		'data-4x': asset('images/posts/IMPERATRITY/data-4x.jpg'),
		fullScreen: asset('images/posts/IMPERATRITY/fullscreen.jpg'),
	},
	{
		id: 'ZA-CAS-DO-RASSVETA',
		title: 'ЗА ЧАС ДО РАССВЕТА',
		src: asset('images/posts/ZA-CAS-DO-RASSVETA/src.jpeg'),
		'data-high-res': asset('images/posts/ZA-CAS-DO-RASSVETA/data-high-res.jpeg'),
		'data-4x': null,
		fullScreen: asset('images/posts/ZA-CAS-DO-RASSVETA/fullscreen.jpeg'),
	},
	{
		id: 'KRASNYI-SELK',
		title: 'Красный шелк',
		src: asset('images/posts/KRASNYI-SELK/src.jpg'),
		'data-high-res': asset('images/posts/KRASNYI-SELK/data-high-res.jpg'),
		'data-4x': asset('images/posts/KRASNYI-SELK/data-4x.jpg'),
		fullScreen: asset('images/posts/KRASNYI-SELK/fullscreen.jpg'),
	},
	{
		id: 'KRASNYI-SELK-PERSONAZNYI-POSTER',
		title: 'Красный шёлк. Персонажный постер',
		src: asset('images/posts/KRASNYI-SELK-PERSONAZNYI-POSTER/src.jpg'),
		'data-high-res': asset('images/posts/KRASNYI-SELK-PERSONAZNYI-POSTER/data-high-res.jpg'),
		'data-4x': asset('images/posts/KRASNYI-SELK-PERSONAZNYI-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/KRASNYI-SELK-PERSONAZNYI-POSTER/fullscreen.jpg'),
	},
	{
		id: 'TRIBUNTEV',
		title: 'Трибунцев',
		src: asset('images/posts/TRIBUNTEV/src.jpg'),
		'data-high-res': asset('images/posts/TRIBUNTEV/data-high-res.jpg'),
		'data-4x': asset('images/posts/TRIBUNTEV/data-4x.jpg'),
		fullScreen: asset('images/posts/TRIBUNTEV/fullscreen.jpg'),
	},
	{
		id: 'KRYL-Y-NAD-BERLINOM',
		title: 'Крылья над Берлином',
		src: asset('images/posts/KRYL-Y-NAD-BERLINOM/src.jpg'),
		'data-high-res': asset('images/posts/KRYL-Y-NAD-BERLINOM/data-high-res.jpg'),
		'data-4x': asset('images/posts/KRYL-Y-NAD-BERLINOM/data-4x.jpg'),
		fullScreen: asset('images/posts/KRYL-Y-NAD-BERLINOM/fullscreen.jpg'),
	},
	{
		id: 'POSLEDOVATELI',
		title: 'ПОСЛЕДОВАТЕЛИ',
		src: asset('images/posts/POSLEDOVATELI/src.jpg'),
		'data-high-res': asset('images/posts/POSLEDOVATELI/data-high-res.jpg'),
		'data-4x': asset('images/posts/POSLEDOVATELI/data-4x.jpg'),
		fullScreen: asset('images/posts/POSLEDOVATELI/fullscreen.jpg'),
	},
	{
		id: 'POZYVNOI-ZURAVLI',
		title: 'Позывной Журавли',
		src: asset('images/posts/POZYVNOI-ZURAVLI/src.jpg'),
		'data-high-res': asset('images/posts/POZYVNOI-ZURAVLI/data-high-res.jpg'),
		'data-4x': asset('images/posts/POZYVNOI-ZURAVLI/data-4x.jpg'),
		fullScreen: asset('images/posts/POZYVNOI-ZURAVLI/fullscreen.jpg'),
	},
	{
		id: 'SLOVO-PATANA-KROV-NA-ASFAL-TE',
		title: '',
		src: asset('images/posts/SLOVO-PATANA-KROV-NA-ASFAL-TE/src.jpg'),
		'data-high-res': asset('images/posts/SLOVO-PATANA-KROV-NA-ASFAL-TE/data-high-res.jpg'),
		'data-4x': asset('images/posts/SLOVO-PATANA-KROV-NA-ASFAL-TE/data-4x.jpg'),
		fullScreen: asset('images/posts/SLOVO-PATANA-KROV-NA-ASFAL-TE/fullscreen.jpg'),
	},
	{
		id: 'NUUCCA',
		title: 'НУУЧЧА',
		src: asset('images/posts/NUUCCA/src.jpg'),
		'data-high-res': asset('images/posts/NUUCCA/data-high-res.jpg'),
		'data-4x': asset('images/posts/NUUCCA/data-4x.jpg'),
		fullScreen: asset('images/posts/NUUCCA/fullscreen.jpg'),
	},
	{
		id: 'ONEGIN-1',
		title: 'Онегин',
		src: asset('images/posts/ONEGIN-1/src.jpg'),
		'data-high-res': asset('images/posts/ONEGIN-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/ONEGIN-1/data-4x.jpg'),
		fullScreen: asset('images/posts/ONEGIN-1/fullscreen.jpg'),
	},
	{
		id: 'ONEGIN',
		title: 'Онегин',
		src: asset('images/posts/ONEGIN/src.jpg'),
		'data-high-res': asset('images/posts/ONEGIN/data-high-res.jpg'),
		'data-4x': asset('images/posts/ONEGIN/data-4x.jpg'),
		fullScreen: asset('images/posts/ONEGIN/fullscreen.jpg'),
	},
	{
		id: 'PRIVOROT-CERNOE-VENCANIE',
		title: 'ПРИВОРОТ: ЧЕРНОЕ ВЕНЧАНИЕ',
		src: asset('images/posts/PRIVOROT-CERNOE-VENCANIE/src.jpg'),
		'data-high-res': asset('images/posts/PRIVOROT-CERNOE-VENCANIE/data-high-res.jpg'),
		'data-4x': asset('images/posts/PRIVOROT-CERNOE-VENCANIE/data-4x.jpg'),
		fullScreen: asset('images/posts/PRIVOROT-CERNOE-VENCANIE/fullscreen.jpg'),
	},
	{
		id: 'CIKATILO',
		title: 'ЧИКАТИЛО',
		src: asset('images/posts/CIKATILO/src.jpeg'),
		'data-high-res': asset('images/posts/CIKATILO/data-high-res.jpeg'),
		'data-4x': asset('images/posts/CIKATILO/data-4x.jpeg'),
		fullScreen: asset('images/posts/CIKATILO/fullscreen.jpeg'),
	},
	{
		id: 'ZDOROVYI-CELOVEK',
		title: 'Здоровый человек',
		src: asset('images/posts/ZDOROVYI-CELOVEK/src.jpg'),
		'data-high-res': asset('images/posts/ZDOROVYI-CELOVEK/data-high-res.jpg'),
		'data-4x': asset('images/posts/ZDOROVYI-CELOVEK/data-4x.jpg'),
		fullScreen: asset('images/posts/ZDOROVYI-CELOVEK/fullscreen.jpg'),
	},
	{
		id: 'LEDYNOI-DEMON',
		title: 'Ледяной демон',
		src: asset('images/posts/LEDYNOI-DEMON/src.jpg'),
		'data-high-res': asset('images/posts/LEDYNOI-DEMON/data-high-res.jpg'),
		'data-4x': asset('images/posts/LEDYNOI-DEMON/data-4x.jpg'),
		fullScreen: asset('images/posts/LEDYNOI-DEMON/fullscreen.jpg'),
	},
	{
		id: 'ICE-DEMON',
		title: 'ICE DEMON',
		src: asset('images/posts/ICE-DEMON/src.jpg'),
		'data-high-res': asset('images/posts/ICE-DEMON/data-high-res.jpg'),
		'data-4x': asset('images/posts/ICE-DEMON/data-4x.jpg'),
		fullScreen: asset('images/posts/ICE-DEMON/fullscreen.jpg'),
	},
	{
		id: 'BERI-DA-POMNI',
		title: 'БЕРИ ДА ПОМНИ',
		src: asset('images/posts/BERI-DA-POMNI/src.jpg'),
		'data-high-res': asset('images/posts/BERI-DA-POMNI/data-high-res.jpg'),
		'data-4x': asset('images/posts/BERI-DA-POMNI/data-4x.jpg'),
		fullScreen: asset('images/posts/BERI-DA-POMNI/fullscreen.jpg'),
	},
	{
		id: 'PIRATY-GALAKTIKI-BARRAKUDA',
		title: 'Пираты галактики Барракуда',
		src: asset('images/posts/PIRATY-GALAKTIKI-BARRAKUDA/src.jpg'),
		'data-high-res': asset('images/posts/PIRATY-GALAKTIKI-BARRAKUDA/data-high-res.jpg'),
		'data-4x': asset('images/posts/PIRATY-GALAKTIKI-BARRAKUDA/data-4x.jpg'),
		fullScreen: asset('images/posts/PIRATY-GALAKTIKI-BARRAKUDA/fullscreen.jpg'),
	},
	{
		id: 'DUK-BAIKALA',
		title: 'Дух Байкала',
		src: asset('images/posts/DUK-BAIKALA/src.jpg'),
		'data-high-res': asset('images/posts/DUK-BAIKALA/data-high-res.jpg'),
		'data-4x': asset('images/posts/DUK-BAIKALA/data-4x.jpg'),
		fullScreen: asset('images/posts/DUK-BAIKALA/fullscreen.jpg'),
	},
	{
		id: 'PRAVEDNIK',
		title: 'Праведник',
		src: asset('images/posts/PRAVEDNIK/src.jpg'),
		'data-high-res': asset('images/posts/PRAVEDNIK/data-high-res.jpg'),
		'data-4x': asset('images/posts/PRAVEDNIK/data-4x.jpg'),
		fullScreen: asset('images/posts/PRAVEDNIK/fullscreen.jpg'),
	},
	{
		id: 'PETR-1',
		title: 'Петр 1',
		src: asset('images/posts/PETR-1/src.jpg'),
		'data-high-res': asset('images/posts/PETR-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/PETR-1/data-4x.jpg'),
		fullScreen: asset('images/posts/PETR-1/fullscreen.jpg'),
	},
	{
		id: 'KOMA',
		title: 'КОМА',
		src: asset('images/posts/KOMA/src.jpg'),
		'data-high-res': asset('images/posts/KOMA/data-high-res.jpg'),
		'data-4x': asset('images/posts/KOMA/data-4x.jpg'),
		fullScreen: asset('images/posts/KOMA/fullscreen.jpg'),
	},
	{
		id: 'SVOBODNYE-OTNOSENIY',
		title: 'СВОБОДНЫЕ ОТНОШЕНИЯ',
		src: asset('images/posts/SVOBODNYE-OTNOSENIY/src.jpg'),
		'data-high-res': asset('images/posts/SVOBODNYE-OTNOSENIY/data-high-res.jpg'),
		'data-4x': asset('images/posts/SVOBODNYE-OTNOSENIY/data-4x.jpg'),
		fullScreen: asset('images/posts/SVOBODNYE-OTNOSENIY/fullscreen.jpg'),
	},
	{
		id: 'BRAT-Y',
		title: 'Братья',
		src: asset('images/posts/BRAT-Y/src.jpg'),
		'data-high-res': asset('images/posts/BRAT-Y/data-high-res.jpg'),
		'data-4x': asset('images/posts/BRAT-Y/data-4x.jpg'),
		fullScreen: asset('images/posts/BRAT-Y/fullscreen.jpg'),
	},
	{
		id: 'BESENSTVO',
		title: 'Бешенство',
		src: asset('images/posts/BESENSTVO/src.jpg'),
		'data-high-res': asset('images/posts/BESENSTVO/data-high-res.jpg'),
		'data-4x': asset('images/posts/BESENSTVO/data-4x.jpg'),
		fullScreen: asset('images/posts/BESENSTVO/fullscreen.jpg'),
	},
	{
		id: 'PLAKAT-NEL-ZY',
		title: 'Плакать нельзя',
		src: asset('images/posts/PLAKAT-NEL-ZY/src.jpg'),
		'data-high-res': asset('images/posts/PLAKAT-NEL-ZY/data-high-res.jpg'),
		'data-4x': asset('images/posts/PLAKAT-NEL-ZY/data-4x.jpg'),
		fullScreen: asset('images/posts/PLAKAT-NEL-ZY/fullscreen.jpg'),
	},
	{
		id: 'VOSEM-SOTEN',
		title: 'ВОСЕМЬ СОТЕН',
		src: asset('images/posts/VOSEM-SOTEN/src.jpg'),
		'data-high-res': asset('images/posts/VOSEM-SOTEN/data-high-res.jpg'),
		'data-4x': asset('images/posts/VOSEM-SOTEN/data-4x.jpg'),
		fullScreen: asset('images/posts/VOSEM-SOTEN/fullscreen.jpg'),
	},
	{
		id: 'LYBOPYTNAY-VARVARA',
		title: 'Любопытная Варвара',
		src: asset('images/posts/LYBOPYTNAY-VARVARA/src.jpg'),
		'data-high-res': asset('images/posts/LYBOPYTNAY-VARVARA/data-high-res.jpg'),
		'data-4x': asset('images/posts/LYBOPYTNAY-VARVARA/data-4x.jpg'),
		fullScreen: asset('images/posts/LYBOPYTNAY-VARVARA/fullscreen.jpg'),
	},
	{
		id: 'CEBURASKA',
		title: 'ЧЕБУРАШКА',
		src: asset('images/posts/CEBURASKA/src.jpg'),
		'data-high-res': asset('images/posts/CEBURASKA/data-high-res.jpg'),
		'data-4x': asset('images/posts/CEBURASKA/data-4x.jpg'),
		fullScreen: asset('images/posts/CEBURASKA/fullscreen.jpg'),
	},
	{
		id: 'MAIOR-GROM-1',
		title: 'Майор гром',
		src: asset('images/posts/MAIOR-GROM-1/src.jpeg'),
		'data-high-res': asset('images/posts/MAIOR-GROM-1/data-high-res.jpeg'),
		'data-4x': null,
		fullScreen: asset('images/posts/MAIOR-GROM-1/fullscreen.jpeg'),
	},
	{
		id: 'MARA',
		title: 'MARA',
		src: asset('images/posts/MARA/src.jpg'),
		'data-high-res': asset('images/posts/MARA/data-high-res.jpg'),
		'data-4x': asset('images/posts/MARA/data-4x.jpg'),
		fullScreen: asset('images/posts/MARA/fullscreen.jpg'),
	},
	{
		id: 'KRASNYI-PRIZRAK',
		title: 'КРАСНЫЙ ПРИЗРАК',
		src: asset('images/posts/KRASNYI-PRIZRAK/src.jpg'),
		'data-high-res': asset('images/posts/KRASNYI-PRIZRAK/data-high-res.jpg'),
		'data-4x': asset('images/posts/KRASNYI-PRIZRAK/data-4x.jpg'),
		fullScreen: asset('images/posts/KRASNYI-PRIZRAK/fullscreen.jpg'),
	},
	{
		id: 'POBOCNYI-EFFEKT',
		title: 'ПОБОЧНЫЙ ЭФФЕКТ',
		src: asset('images/posts/POBOCNYI-EFFEKT/src.jpg'),
		'data-high-res': asset('images/posts/POBOCNYI-EFFEKT/data-high-res.jpg'),
		'data-4x': asset('images/posts/POBOCNYI-EFFEKT/data-4x.jpg'),
		fullScreen: asset('images/posts/POBOCNYI-EFFEKT/fullscreen.jpg'),
	},
	{
		id: 'VOLAND',
		title: 'ВОЛАНД',
		src: asset('images/posts/VOLAND/src.jpg'),
		'data-high-res': asset('images/posts/VOLAND/data-high-res.jpg'),
		'data-4x': asset('images/posts/VOLAND/data-4x.jpg'),
		fullScreen: asset('images/posts/VOLAND/fullscreen.jpg'),
	},
	{
		id: 'CIKI',
		title: 'ЧИКИ',
		src: asset('images/posts/CIKI/src.jpg'),
		'data-high-res': asset('images/posts/CIKI/data-high-res.jpg'),
		'data-4x': asset('images/posts/CIKI/data-4x.jpg'),
		fullScreen: asset('images/posts/CIKI/fullscreen.jpg'),
	},
	{
		id: 'KOL-SKAY-SVERKGLUBOKAY',
		title: 'КОЛЬСКАЯ СВЕРХГЛУБОКАЯ',
		src: asset('images/posts/KOL-SKAY-SVERKGLUBOKAY/src.jpg'),
		'data-high-res': asset('images/posts/KOL-SKAY-SVERKGLUBOKAY/data-high-res.jpg'),
		'data-4x': asset('images/posts/KOL-SKAY-SVERKGLUBOKAY/data-4x.jpg'),
		fullScreen: asset('images/posts/KOL-SKAY-SVERKGLUBOKAY/fullscreen.jpg'),
	},
	{
		id: 'SERDTE-PARMY',
		title: 'СЕРДЦЕ ПАРМЫ',
		src: asset('images/posts/SERDTE-PARMY/src.jpg'),
		'data-high-res': asset('images/posts/SERDTE-PARMY/data-high-res.jpg'),
		'data-4x': asset('images/posts/SERDTE-PARMY/data-4x.jpg'),
		fullScreen: asset('images/posts/SERDTE-PARMY/fullscreen.jpg'),
	},
	{
		id: 'SERDTE-PARMY-1',
		title: 'СЕРДЦЕ ПАРМЫ',
		src: asset('images/posts/SERDTE-PARMY-1/src.jpg'),
		'data-high-res': asset('images/posts/SERDTE-PARMY-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/SERDTE-PARMY-1/data-4x.jpg'),
		fullScreen: asset('images/posts/SERDTE-PARMY-1/fullscreen.jpg'),
	},
	{
		id: 'THE-EX',
		title: 'THE EX',
		src: asset('images/posts/THE-EX/src.jpg'),
		'data-high-res': asset('images/posts/THE-EX/data-high-res.jpg'),
		'data-4x': asset('images/posts/THE-EX/data-4x.jpg'),
		fullScreen: asset('images/posts/THE-EX/fullscreen.jpg'),
	},
	{
		id: 'AVANPOST',
		title: 'АВАНПОСТ',
		src: asset('images/posts/AVANPOST/src.jpg'),
		'data-high-res': asset('images/posts/AVANPOST/data-high-res.jpg'),
		'data-4x': asset('images/posts/AVANPOST/data-4x.jpg'),
		fullScreen: asset('images/posts/AVANPOST/fullscreen.jpg'),
	},
	{
		id: 'SERLOK-V-ROSSII',
		title: 'ШЕРЛОК В РОССИИ',
		src: asset('images/posts/SERLOK-V-ROSSII/src.jpg'),
		'data-high-res': asset('images/posts/SERLOK-V-ROSSII/data-high-res.jpg'),
		'data-4x': asset('images/posts/SERLOK-V-ROSSII/data-4x.jpg'),
		fullScreen: asset('images/posts/SERLOK-V-ROSSII/fullscreen.jpg'),
	},
	{
		id: 'PODOL-SKIE-KURSANTY-KARAKTER-POSTER',
		title: 'ПОДОЛЬСКИЕ КУРСАНТЫ (характер постер)',
		src: asset('images/posts/PODOL-SKIE-KURSANTY-KARAKTER-POSTER/src.jpg'),
		'data-high-res': asset(
			'images/posts/PODOL-SKIE-KURSANTY-KARAKTER-POSTER/data-high-res.jpg'
		),
		'data-4x': asset('images/posts/PODOL-SKIE-KURSANTY-KARAKTER-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/PODOL-SKIE-KURSANTY-KARAKTER-POSTER/fullscreen.jpg'),
	},
	{
		id: 'KOMA_PERSONAZNYE-POSTERY',
		title: 'КОМА_ПЕРСОНАЖНЫЕ ПОСТЕРЫ',
		src: asset('images/posts/KOMA_PERSONAZNYE-POSTERY/src.jpg'),
		'data-high-res': asset('images/posts/KOMA_PERSONAZNYE-POSTERY/data-high-res.jpg'),
		'data-4x': asset('images/posts/KOMA_PERSONAZNYE-POSTERY/data-4x.jpg'),
		fullScreen: asset('images/posts/KOMA_PERSONAZNYE-POSTERY/fullscreen.jpg'),
	},
	{
		id: 'KOCUVIGRU',
		title: 'ХОЧУВИГРУ',
		src: asset('images/posts/KOCUVIGRU/src.jpeg'),
		'data-high-res': asset('images/posts/KOCUVIGRU/data-high-res.jpeg'),
		'data-4x': asset('images/posts/KOCUVIGRU/data-4x.jpeg'),
		fullScreen: asset('images/posts/KOCUVIGRU/fullscreen.jpeg'),
	},
	{
		id: 'DYLDA',
		title: 'Дылда',
		src: asset('images/posts/DYLDA/src.jpg'),
		'data-high-res': asset('images/posts/DYLDA/data-high-res.jpg'),
		'data-4x': asset('images/posts/DYLDA/data-4x.jpg'),
		fullScreen: asset('images/posts/DYLDA/fullscreen.jpg'),
	},
	{
		id: 'VDOVA',
		title: 'Вдова',
		src: asset('images/posts/VDOVA/src.jpg'),
		'data-high-res': asset('images/posts/VDOVA/data-high-res.jpg'),
		'data-4x': asset('images/posts/VDOVA/data-4x.jpg'),
		fullScreen: asset('images/posts/VDOVA/fullscreen.jpg'),
	},
	{
		id: 'AVANPOST-1',
		title: 'АВАНПОСТ',
		src: asset('images/posts/AVANPOST-1/src.jpg'),
		'data-high-res': asset('images/posts/AVANPOST-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/AVANPOST-1/data-4x.jpg'),
		fullScreen: asset('images/posts/AVANPOST-1/fullscreen.jpg'),
	},
	{
		id: 'RAZZIMAY-KULAKI',
		title: 'Разжимая кулаки',
		src: asset('images/posts/RAZZIMAY-KULAKI/src.jpg'),
		'data-high-res': asset('images/posts/RAZZIMAY-KULAKI/data-high-res.jpg'),
		'data-4x': asset('images/posts/RAZZIMAY-KULAKI/data-4x.jpg'),
		fullScreen: asset('images/posts/RAZZIMAY-KULAKI/fullscreen.jpg'),
	},
	{
		id: 'DOC-RYBAKA',
		title: 'ДОЧЬ РЫБАКА',
		src: asset('images/posts/DOC-RYBAKA/src.jpg'),
		'data-high-res': asset('images/posts/DOC-RYBAKA/data-high-res.jpg'),
		'data-4x': asset('images/posts/DOC-RYBAKA/data-4x.jpg'),
		fullScreen: asset('images/posts/DOC-RYBAKA/fullscreen.jpg'),
	},
	{
		id: 'OBSAGA',
		title: 'ОБЩАГА',
		src: asset('images/posts/OBSAGA/src.jpg'),
		'data-high-res': asset('images/posts/OBSAGA/data-high-res.jpg'),
		'data-4x': asset('images/posts/OBSAGA/data-4x.jpg'),
		fullScreen: asset('images/posts/OBSAGA/fullscreen.jpg'),
	},
	{
		id: 'SPASTI-LENINGRAD',
		title: 'Спасти Ленинград',
		src: asset('images/posts/SPASTI-LENINGRAD/src.jpg'),
		'data-high-res': asset('images/posts/SPASTI-LENINGRAD/data-high-res.jpg'),
		'data-4x': asset('images/posts/SPASTI-LENINGRAD/data-4x.jpg'),
		fullScreen: asset('images/posts/SPASTI-LENINGRAD/fullscreen.jpg'),
	},
	{
		id: 'YGY-KOSMAR-TEMNOGO-LESA',
		title: 'ЯГЯ:КОШМАР ТЁМНОГО ЛЕСА',
		src: asset('images/posts/YGY-KOSMAR-TEMNOGO-LESA/src.jpg'),
		'data-high-res': asset('images/posts/YGY-KOSMAR-TEMNOGO-LESA/data-high-res.jpg'),
		'data-4x': asset('images/posts/YGY-KOSMAR-TEMNOGO-LESA/data-4x.jpg'),
		fullScreen: asset('images/posts/YGY-KOSMAR-TEMNOGO-LESA/fullscreen.jpg'),
	},
	{
		id: 'MERMAID',
		title: 'MERMAID',
		src: asset('images/posts/MERMAID/src.jpg'),
		'data-high-res': asset('images/posts/MERMAID/data-high-res.jpg'),
		'data-4x': asset('images/posts/MERMAID/data-4x.jpg'),
		fullScreen: asset('images/posts/MERMAID/fullscreen.jpg'),
	},
	{
		id: 'PRIVOROT',
		title: 'ПРИВОРОТ',
		src: asset('images/posts/PRIVOROT/src.jpg'),
		'data-high-res': asset('images/posts/PRIVOROT/data-high-res.jpg'),
		'data-4x': asset('images/posts/PRIVOROT/data-4x.jpg'),
		fullScreen: asset('images/posts/PRIVOROT/fullscreen.jpg'),
	},
	{
		id: 'PAPA-SDOKNI',
		title: 'ПАПА, СДОХНИ',
		src: asset('images/posts/PAPA-SDOKNI/src.jpg'),
		'data-high-res': asset('images/posts/PAPA-SDOKNI/data-high-res.jpg'),
		'data-4x': asset('images/posts/PAPA-SDOKNI/data-4x.jpg'),
		fullScreen: asset('images/posts/PAPA-SDOKNI/fullscreen.jpg'),
	},
	{
		id: 'NEBESNAY-KOMANDA',
		title: 'Небесная команда',
		src: asset('images/posts/NEBESNAY-KOMANDA/src.jpeg'),
		'data-high-res': asset('images/posts/NEBESNAY-KOMANDA/data-high-res.jpeg'),
		'data-4x': asset('images/posts/NEBESNAY-KOMANDA/data-4x.jpeg'),
		fullScreen: asset('images/posts/NEBESNAY-KOMANDA/fullscreen.jpeg'),
	},
	{
		id: 'IDENTIFIKATIY',
		title: 'Идентификация',
		src: asset('images/posts/IDENTIFIKATIY/src.jpg'),
		'data-high-res': asset('images/posts/IDENTIFIKATIY/data-high-res.jpg'),
		'data-4x': asset('images/posts/IDENTIFIKATIY/data-4x.jpg'),
		fullScreen: asset('images/posts/IDENTIFIKATIY/fullscreen.jpg'),
	},
	{
		id: 'TEKST',
		title: 'ТЕКСТ',
		src: asset('images/posts/TEKST/src.jpg'),
		'data-high-res': asset('images/posts/TEKST/data-high-res.jpg'),
		'data-4x': asset('images/posts/TEKST/data-4x.jpg'),
		fullScreen: asset('images/posts/TEKST/fullscreen.jpg'),
	},
	{
		id: 'BALKANSKII-RUBEZ',
		title: 'БАЛКАНСКИЙ РУБЕЖ',
		src: asset('images/posts/BALKANSKII-RUBEZ/src.jpg'),
		'data-high-res': asset('images/posts/BALKANSKII-RUBEZ/data-high-res.jpg'),
		'data-4x': asset('images/posts/BALKANSKII-RUBEZ/data-4x.jpg'),
		fullScreen: asset('images/posts/BALKANSKII-RUBEZ/fullscreen.jpg'),
	},
	{
		id: 'KONVERT',
		title: 'КОНВЕРТ',
		src: asset('images/posts/KONVERT/src.jpg'),
		'data-high-res': asset('images/posts/KONVERT/data-high-res.jpg'),
		'data-4x': asset('images/posts/KONVERT/data-4x.jpg'),
		fullScreen: asset('images/posts/KONVERT/fullscreen.jpg'),
	},
	{
		id: 'DECISION-LIQUIDATION',
		title: 'DECISION:LIQUIDATION',
		src: asset('images/posts/DECISION-LIQUIDATION/src.jpg'),
		'data-high-res': asset('images/posts/DECISION-LIQUIDATION/data-high-res.jpg'),
		'data-4x': asset('images/posts/DECISION-LIQUIDATION/data-4x.jpg'),
		fullScreen: asset('images/posts/DECISION-LIQUIDATION/fullscreen.jpg'),
	},
	{
		id: 'T-34-TIZER-POSTER',
		title: 'Т-34 тизер постер',
		src: asset('images/posts/T-34-TIZER-POSTER/src.jpg'),
		'data-high-res': asset('images/posts/T-34-TIZER-POSTER/data-high-res.jpg'),
		'data-4x': asset('images/posts/T-34-TIZER-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/T-34-TIZER-POSTER/fullscreen.jpg'),
	},
	{
		id: 'SELFI',
		title: 'СЕЛФИ',
		src: asset('images/posts/SELFI/src.jpg'),
		'data-high-res': asset('images/posts/SELFI/data-high-res.jpg'),
		'data-4x': asset('images/posts/SELFI/data-4x.jpg'),
		fullScreen: asset('images/posts/SELFI/fullscreen.jpg'),
	},
	{
		id: 'LED-2-PERSONAZNYI-POSTER',
		title: 'ЛЁД 2 персонажный постер',
		src: asset('images/posts/LED-2-PERSONAZNYI-POSTER/src.jpg'),
		'data-high-res': asset('images/posts/LED-2-PERSONAZNYI-POSTER/data-high-res.jpg'),
		'data-4x': asset('images/posts/LED-2-PERSONAZNYI-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/LED-2-PERSONAZNYI-POSTER/fullscreen.jpg'),
	},
	{
		id: 'IDENTIFICATION',
		title: 'IDENTIFICATION',
		src: asset('images/posts/IDENTIFICATION/src.jpg'),
		'data-high-res': asset('images/posts/IDENTIFICATION/data-high-res.jpg'),
		'data-4x': asset('images/posts/IDENTIFICATION/data-4x.jpg'),
		fullScreen: asset('images/posts/IDENTIFICATION/fullscreen.jpg'),
	},
	{
		id: '28-PANFILOVTEV',
		title: '28 ПАНФИЛОВЦЕВ',
		src: asset('images/posts/28-PANFILOVTEV/src.jpg'),
		'data-high-res': asset('images/posts/28-PANFILOVTEV/data-high-res.jpg'),
		'data-4x': asset('images/posts/28-PANFILOVTEV/data-4x.jpg'),
		fullScreen: asset('images/posts/28-PANFILOVTEV/fullscreen.jpg'),
	},
	{
		id: 'MIFY',
		title: 'МИФЫ',
		src: asset('images/posts/MIFY/src.jpg'),
		'data-high-res': asset('images/posts/MIFY/data-high-res.jpg'),
		'data-4x': asset('images/posts/MIFY/data-4x.jpg'),
		fullScreen: asset('images/posts/MIFY/fullscreen.jpg'),
	},
	{
		id: 'KUPI-MENY',
		title: 'КУПИ МЕНЯ',
		src: asset('images/posts/KUPI-MENY/src.jpg'),
		'data-high-res': asset('images/posts/KUPI-MENY/data-high-res.jpg'),
		'data-4x': asset('images/posts/KUPI-MENY/data-4x.jpg'),
		fullScreen: asset('images/posts/KUPI-MENY/fullscreen.jpg'),
	},
	{
		id: 'LED',
		title: 'ЛЁД',
		src: asset('images/posts/LED/src.jpg'),
		'data-high-res': asset('images/posts/LED/data-high-res.jpg'),
		'data-4x': asset('images/posts/LED/data-4x.jpg'),
		fullScreen: asset('images/posts/LED/fullscreen.jpg'),
	},
	{
		id: 'MILLIARD-TIZER-POSTER',
		title: 'МИЛЛИАРД. тизер постер',
		src: asset('images/posts/MILLIARD-TIZER-POSTER/src.jpg'),
		'data-high-res': asset('images/posts/MILLIARD-TIZER-POSTER/data-high-res.jpg'),
		'data-4x': asset('images/posts/MILLIARD-TIZER-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/MILLIARD-TIZER-POSTER/fullscreen.jpg'),
	},
	{
		id: 'RUSALKA',
		title: 'РУСАЛКА',
		src: asset('images/posts/RUSALKA/src.jpg'),
		'data-high-res': asset('images/posts/RUSALKA/data-high-res.jpg'),
		'data-4x': asset('images/posts/RUSALKA/data-4x.jpg'),
		fullScreen: asset('images/posts/RUSALKA/fullscreen.jpg'),
	},
	{
		id: 'POSLE-TEBY',
		title: 'ПОСЛЕ ТЕБЯ',
		src: asset('images/posts/POSLE-TEBY/src.jpg'),
		'data-high-res': asset('images/posts/POSLE-TEBY/data-high-res.jpg'),
		'data-4x': asset('images/posts/POSLE-TEBY/data-4x.jpg'),
		fullScreen: asset('images/posts/POSLE-TEBY/fullscreen.jpg'),
	},
	{
		id: 'ZGI',
		title: 'ЖГИ',
		src: asset('images/posts/ZGI/src.jpg'),
		'data-high-res': asset('images/posts/ZGI/data-high-res.jpg'),
		'data-4x': asset('images/posts/ZGI/data-4x.jpg'),
		fullScreen: asset('images/posts/ZGI/fullscreen.jpg'),
	},
	{
		id: 'Y-KUDEY',
		title: 'Я Худею',
		src: asset('images/posts/Y-KUDEY/src.jpg'),
		'data-high-res': asset('images/posts/Y-KUDEY/data-high-res.jpg'),
		'data-4x': asset('images/posts/Y-KUDEY/data-4x.jpg'),
		fullScreen: asset('images/posts/Y-KUDEY/fullscreen.jpg'),
	},
	{
		id: 'MAIOR-GROM',
		title: 'МАЙОР ГРОМ',
		src: asset('images/posts/MAIOR-GROM/src.jpg'),
		'data-high-res': asset('images/posts/MAIOR-GROM/data-high-res.jpg'),
		'data-4x': asset('images/posts/MAIOR-GROM/data-4x.jpg'),
		fullScreen: asset('images/posts/MAIOR-GROM/fullscreen.jpg'),
	},
	{
		id: 'MAIOR-GROM-PERSONAZNYI-POSTER',
		title: 'МАЙОР ГРОМ: ПЕРСОНАЖНЫЙ ПОСТЕР',
		src: asset('images/posts/MAIOR-GROM-PERSONAZNYI-POSTER/src.jpg'),
		'data-high-res': asset('images/posts/MAIOR-GROM-PERSONAZNYI-POSTER/data-high-res.jpg'),
		'data-4x': asset('images/posts/MAIOR-GROM-PERSONAZNYI-POSTER/data-4x.jpg'),
		fullScreen: asset('images/posts/MAIOR-GROM-PERSONAZNYI-POSTER/fullscreen.jpg'),
	},
	{
		id: 'PROVODNIK',
		title: 'ПРОВОДНИК',
		src: asset('images/posts/PROVODNIK/src.jpg'),
		'data-high-res': asset('images/posts/PROVODNIK/data-high-res.jpg'),
		'data-4x': asset('images/posts/PROVODNIK/data-4x.jpg'),
		fullScreen: asset('images/posts/PROVODNIK/fullscreen.jpg'),
	},
	{
		id: 'FOTO-NA-PAMYT-TIZER',
		title: 'ФОТО НА ПАМЯТЬ: ТИЗЕР',
		src: asset('images/posts/FOTO-NA-PAMYT-TIZER/src.jpg'),
		'data-high-res': asset('images/posts/FOTO-NA-PAMYT-TIZER/data-high-res.jpg'),
		'data-4x': asset('images/posts/FOTO-NA-PAMYT-TIZER/data-4x.jpg'),
		fullScreen: asset('images/posts/FOTO-NA-PAMYT-TIZER/fullscreen.jpg'),
	},
	{
		id: 'NEVESTA',
		title: 'НЕВЕСТА',
		src: asset('images/posts/NEVESTA/src.jpg'),
		'data-high-res': asset('images/posts/NEVESTA/data-high-res.jpg'),
		'data-4x': asset('images/posts/NEVESTA/data-4x.jpg'),
		fullScreen: asset('images/posts/NEVESTA/fullscreen.jpg'),
	},
	{
		id: 'NA-RAIONE-TIZER',
		title: 'НА РАЙОНЕ:ТИЗЕР',
		src: asset('images/posts/NA-RAIONE-TIZER/src.jpg'),
		'data-high-res': asset('images/posts/NA-RAIONE-TIZER/data-high-res.jpg'),
		'data-4x': asset('images/posts/NA-RAIONE-TIZER/data-4x.jpg'),
		fullScreen: asset('images/posts/NA-RAIONE-TIZER/fullscreen.jpg'),
	},
	{
		id: 'ZEMLETRYSENIE',
		title: 'ЗЕМЛЕТРЯСЕНИЕ',
		src: asset('images/posts/ZEMLETRYSENIE/src.jpg'),
		'data-high-res': asset('images/posts/ZEMLETRYSENIE/data-high-res.jpg'),
		'data-4x': asset('images/posts/ZEMLETRYSENIE/data-4x.jpg'),
		fullScreen: asset('images/posts/ZEMLETRYSENIE/fullscreen.jpg'),
	},
	{
		id: 'ZEMLETRYSENIE-1',
		title: 'ЗЕМЛЕТРЯСЕНИЕ',
		src: asset('images/posts/ZEMLETRYSENIE-1/src.jpg'),
		'data-high-res': asset('images/posts/ZEMLETRYSENIE-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/ZEMLETRYSENIE-1/data-4x.jpg'),
		fullScreen: asset('images/posts/ZEMLETRYSENIE-1/fullscreen.jpg'),
	},
	{
		id: 'GUARDIANS_CHARACTER-POSTER-3',
		title: 'GUARDIANS_CHARACTER POSTER#3',
		src: asset('images/posts/GUARDIANS_CHARACTER-POSTER-3/src.jpg'),
		'data-high-res': asset('images/posts/GUARDIANS_CHARACTER-POSTER-3/data-high-res.jpg'),
		'data-4x': asset('images/posts/GUARDIANS_CHARACTER-POSTER-3/data-4x.jpg'),
		fullScreen: asset('images/posts/GUARDIANS_CHARACTER-POSTER-3/fullscreen.jpg'),
	},
	{
		id: 'GUARDIANS_CHARACTER-POSTER-2',
		title: 'GUARDIANS_CHARACTER POSTER#2',
		src: asset('images/posts/GUARDIANS_CHARACTER-POSTER-2/src.jpg'),
		'data-high-res': asset('images/posts/GUARDIANS_CHARACTER-POSTER-2/data-high-res.jpg'),
		'data-4x': asset('images/posts/GUARDIANS_CHARACTER-POSTER-2/data-4x.jpg'),
		fullScreen: asset('images/posts/GUARDIANS_CHARACTER-POSTER-2/fullscreen.jpg'),
	},
	{
		id: 'GUARDIANS_CHARACTER-POSTER_KHAN',
		title: 'GUARDIANS_CHARACTER POSTER_KHAN',
		src: asset('images/posts/GUARDIANS_CHARACTER-POSTER_KHAN/src.jpg'),
		'data-high-res': asset('images/posts/GUARDIANS_CHARACTER-POSTER_KHAN/data-high-res.jpg'),
		'data-4x': asset('images/posts/GUARDIANS_CHARACTER-POSTER_KHAN/data-4x.jpg'),
		fullScreen: asset('images/posts/GUARDIANS_CHARACTER-POSTER_KHAN/fullscreen.jpg'),
	},
	{
		id: 'EKIPAZ-KARAKTER-POSTER-1',
		title: 'ЭКИПАЖ (ХАРАКТЕР ПОСТЕР№1)',
		src: asset('images/posts/EKIPAZ-KARAKTER-POSTER-1/src.jpg'),
		'data-high-res': asset('images/posts/EKIPAZ-KARAKTER-POSTER-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/EKIPAZ-KARAKTER-POSTER-1/data-4x.jpg'),
		fullScreen: asset('images/posts/EKIPAZ-KARAKTER-POSTER-1/fullscreen.jpg'),
	},
	{
		id: 'EKIPAZ-POSTER-1',
		title: 'ЭКИПАЖ, постер №1',
		src: asset('images/posts/EKIPAZ-POSTER-1/src.jpg'),
		'data-high-res': asset('images/posts/EKIPAZ-POSTER-1/data-high-res.jpg'),
		'data-4x': asset('images/posts/EKIPAZ-POSTER-1/data-4x.jpg'),
		fullScreen: asset('images/posts/EKIPAZ-POSTER-1/fullscreen.jpg'),
	},
	{
		id: 'EKIPAZ',
		title: 'ЭКИПАЖ',
		src: asset('images/posts/EKIPAZ/src.jpg'),
		'data-high-res': asset('images/posts/EKIPAZ/data-high-res.jpg'),
		'data-4x': asset('images/posts/EKIPAZ/data-4x.jpg'),
		fullScreen: asset('images/posts/EKIPAZ/fullscreen.jpg'),
	},
	{
		id: 'TIZER-LEDOKOL',
		title: 'ТИЗЕР: ЛЕДОКОЛ',
		src: asset('images/posts/TIZER-LEDOKOL/src.jpg'),
		'data-high-res': asset('images/posts/TIZER-LEDOKOL/data-high-res.jpg'),
		'data-4x': asset('images/posts/TIZER-LEDOKOL/data-4x.jpg'),
		fullScreen: asset('images/posts/TIZER-LEDOKOL/fullscreen.jpg'),
	},
	{
		id: 'DIGGERY',
		title: 'ДИГГЕРЫ',
		src: asset('images/posts/DIGGERY/src.jpg'),
		'data-high-res': asset('images/posts/DIGGERY/data-high-res.jpg'),
		'data-4x': asset('images/posts/DIGGERY/data-4x.jpg'),
		fullScreen: asset('images/posts/DIGGERY/fullscreen.jpg'),
	},
	{
		id: 'DIGGERS_TEASER',
		title: 'DIGGERS_TEASER',
		src: asset('images/posts/DIGGERS_TEASER/src.jpg'),
		'data-high-res': asset('images/posts/DIGGERS_TEASER/data-high-res.jpg'),
		'data-4x': asset('images/posts/DIGGERS_TEASER/data-4x.jpg'),
		fullScreen: asset('images/posts/DIGGERS_TEASER/fullscreen.jpg'),
	},
	{
		id: 'TIZER-PIKOVAY-DAMA-CERNYI-OBRYD',
		title: 'ТИЗЕР ПИКОВАЯ ДАМА: ЧЁРНЫЙ ОБРЯД',
		src: asset('images/posts/TIZER-PIKOVAY-DAMA-CERNYI-OBRYD/src.jpg'),
		'data-high-res': asset('images/posts/TIZER-PIKOVAY-DAMA-CERNYI-OBRYD/data-high-res.jpg'),
		'data-4x': asset('images/posts/TIZER-PIKOVAY-DAMA-CERNYI-OBRYD/data-4x.jpg'),
		fullScreen: asset('images/posts/TIZER-PIKOVAY-DAMA-CERNYI-OBRYD/fullscreen.jpg'),
	},
	{
		id: 'PIKOVAY-DAMA-CERNYI-OBRYD',
		title: 'ПИКОВАЯ ДАМА: ЧЁРНЫЙ ОБРЯД',
		src: asset('images/posts/PIKOVAY-DAMA-CERNYI-OBRYD/src.jpg'),
		'data-high-res': asset('images/posts/PIKOVAY-DAMA-CERNYI-OBRYD/data-high-res.jpg'),
		'data-4x': asset('images/posts/PIKOVAY-DAMA-CERNYI-OBRYD/data-4x.jpg'),
		fullScreen: asset('images/posts/PIKOVAY-DAMA-CERNYI-OBRYD/fullscreen.jpg'),
	},
	{
		id: 'GOSTI',
		title: 'ГОСТИ',
		src: asset('images/posts/GOSTI/src.jpg'),
		'data-high-res': asset('images/posts/GOSTI/data-high-res.jpg'),
		'data-4x': asset('images/posts/GOSTI/data-4x.jpg'),
		fullScreen: asset('images/posts/GOSTI/fullscreen.jpg'),
	},
	{
		id: 'NEZLAMNA',
		title: 'НЕЗЛАМНА',
		src: asset('images/posts/NEZLAMNA/src.jpg'),
		'data-high-res': asset('images/posts/NEZLAMNA/data-high-res.jpg'),
		'data-4x': asset('images/posts/NEZLAMNA/data-4x.jpg'),
		fullScreen: asset('images/posts/NEZLAMNA/fullscreen.jpg'),
	},
	{
		id: 'BITVA-ZA-SEVASTOPOL',
		title: 'БИТВА ЗА СЕВАСТОПОЛЬ',
		src: asset('images/posts/BITVA-ZA-SEVASTOPOL/src.jpg'),
		'data-high-res': asset('images/posts/BITVA-ZA-SEVASTOPOL/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/BITVA-ZA-SEVASTOPOL/fullscreen.jpg'),
	},
	{
		id: 'LEGENDA-O-KOLOVRATE-TIZER',
		title: 'ЛЕГЕНДА О КОЛОВРАТЕ: ТИЗЕР',
		src: asset('images/posts/LEGENDA-O-KOLOVRATE-TIZER/src.jpg'),
		'data-high-res': asset('images/posts/LEGENDA-O-KOLOVRATE-TIZER/data-high-res.jpg'),
		'data-4x': asset('images/posts/LEGENDA-O-KOLOVRATE-TIZER/data-4x.jpg'),
		fullScreen: asset('images/posts/LEGENDA-O-KOLOVRATE-TIZER/fullscreen.jpg'),
	},
	{
		id: 'TEASER_SPECULUM',
		title: 'TEASER_SPECULUM',
		src: asset('images/posts/TEASER_SPECULUM/src.jpg'),
		'data-high-res': asset('images/posts/TEASER_SPECULUM/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/TEASER_SPECULUM/fullscreen.jpg'),
	},
	{
		id: 'RASSVET',
		title: 'РАССВЕТ',
		src: asset('images/posts/RASSVET/src.jpg'),
		'data-high-res': asset('images/posts/RASSVET/data-high-res.jpg'),
		'data-4x': asset('images/posts/RASSVET/data-4x.jpg'),
		fullScreen: asset('images/posts/RASSVET/fullscreen.jpg'),
	},
	{
		id: 'KROVAVAY-LEDI-BATORI',
		title: 'КРОВАВАЯ ЛЕДИ: БАТОРИ',
		src: asset('images/posts/KROVAVAY-LEDI-BATORI/src.jpg'),
		'data-high-res': asset('images/posts/KROVAVAY-LEDI-BATORI/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/KROVAVAY-LEDI-BATORI/fullscreen.jpg'),
	},
	{
		id: 'LYBOV-V-GORODE-ANGELOV',
		title: 'ЛЮБОВЬ В ГОРОДЕ АНГЕЛОВ',
		src: asset('images/posts/LYBOV-V-GORODE-ANGELOV/src.jpg'),
		'data-high-res': asset('images/posts/LYBOV-V-GORODE-ANGELOV/data-high-res.jpg'),
		'data-4x': asset('images/posts/LYBOV-V-GORODE-ANGELOV/data-4x.jpg'),
		fullScreen: asset('images/posts/LYBOV-V-GORODE-ANGELOV/fullscreen.jpg'),
	},
	{
		id: 'TERRITORIY',
		title: 'ТЕРРИТОРИЯ',
		src: asset('images/posts/TERRITORIY/src.jpg'),
		'data-high-res': asset('images/posts/TERRITORIY/data-high-res.jpg'),
		'data-4x': asset('images/posts/TERRITORIY/data-4x.jpg'),
		fullScreen: asset('images/posts/TERRITORIY/fullscreen.jpg'),
	},
	{
		id: 'STATUS-SVOBODEN',
		title: 'СТАТУС СВОБОДЕН',
		src: asset('images/posts/STATUS-SVOBODEN/src.jpg'),
		'data-high-res': asset('images/posts/STATUS-SVOBODEN/data-high-res.jpg'),
		'data-4x': asset('images/posts/STATUS-SVOBODEN/data-4x.jpg'),
		fullScreen: asset('images/posts/STATUS-SVOBODEN/fullscreen.jpg'),
	},
	{
		id: 'ANNA-KARENINA',
		title: 'АННА КАРЕНИНА',
		src: asset('images/posts/ANNA-KARENINA/src.jpg'),
		'data-high-res': asset('images/posts/ANNA-KARENINA/data-high-res.jpg'),
		'data-4x': asset('images/posts/ANNA-KARENINA/data-4x.jpg'),
		fullScreen: asset('images/posts/ANNA-KARENINA/fullscreen.jpg'),
	},
	{
		id: 'MAFIY-IGRA-NA-VYZIVANIE',
		title: 'МАФИЯ: ИГРА НА ВЫЖИВАНИЕ',
		src: asset('images/posts/MAFIY-IGRA-NA-VYZIVANIE/src.jpg'),
		'data-high-res': asset('images/posts/MAFIY-IGRA-NA-VYZIVANIE/data-high-res.jpg'),
		'data-4x': asset('images/posts/MAFIY-IGRA-NA-VYZIVANIE/data-4x.jpg'),
		fullScreen: asset('images/posts/MAFIY-IGRA-NA-VYZIVANIE/fullscreen.jpg'),
	},
	{
		id: 'VOIN',
		title: 'ВОИН',
		src: asset('images/posts/VOIN/src.jpg'),
		'data-high-res': asset('images/posts/VOIN/data-high-res.jpg'),
		'data-4x': asset('images/posts/VOIN/data-4x.jpg'),
		fullScreen: asset('images/posts/VOIN/fullscreen.jpg'),
	},
	{
		id: 'POSLEDNII-GEROI-NEULOVIMYE',
		title: 'ПОСЛЕДНИЙ ГЕРОЙ: НЕУЛОВИМЫЕ',
		src: asset('images/posts/POSLEDNII-GEROI-NEULOVIMYE/src.jpg'),
		'data-high-res': asset('images/posts/POSLEDNII-GEROI-NEULOVIMYE/data-high-res.jpg'),
		'data-4x': asset('images/posts/POSLEDNII-GEROI-NEULOVIMYE/data-4x.jpg'),
		fullScreen: asset('images/posts/POSLEDNII-GEROI-NEULOVIMYE/fullscreen.jpg'),
	},
	{
		id: 'TIZER-1-NEULOVIMYE',
		title: 'ТИЗЕР 1 НЕУЛОВИМЫЕ',
		src: asset('images/posts/TIZER-1-NEULOVIMYE/src.jpg'),
		'data-high-res': asset('images/posts/TIZER-1-NEULOVIMYE/data-high-res.jpg'),
		'data-4x': asset('images/posts/TIZER-1-NEULOVIMYE/data-4x.jpg'),
		fullScreen: asset('images/posts/TIZER-1-NEULOVIMYE/fullscreen.jpg'),
	},
	{
		id: 'SARANCA',
		title: 'САРАНЧА',
		src: asset('images/posts/SARANCA/src.jpg'),
		'data-high-res': asset('images/posts/SARANCA/data-high-res.jpg'),
		'data-4x': asset('images/posts/SARANCA/data-4x.jpg'),
		fullScreen: asset('images/posts/SARANCA/fullscreen.jpg'),
	},
	{
		id: 'SERIAL-RODINA_KONTEPT_-POSTERA-NE-PRINYT',
		title: 'сериал РОДИНА_концепт_ постера(не принят)',
		src: asset('images/posts/SERIAL-RODINA_KONTEPT_-POSTERA-NE-PRINYT/src.jpg'),
		'data-high-res': asset(
			'images/posts/SERIAL-RODINA_KONTEPT_-POSTERA-NE-PRINYT/data-high-res.jpg'
		),
		'data-4x': asset('images/posts/SERIAL-RODINA_KONTEPT_-POSTERA-NE-PRINYT/data-4x.jpg'),
		fullScreen: asset(
			'images/posts/SERIAL-RODINA_KONTEPT_-POSTERA-NE-PRINYT/fullscreen.jpg'
		),
	},
	{
		id: 'DUHLESS2',
		title: 'DUHLESS2',
		src: asset('images/posts/DUHLESS2/src.jpg'),
		'data-high-res': asset('images/posts/DUHLESS2/data-high-res.jpg'),
		'data-4x': asset('images/posts/DUHLESS2/data-4x.jpg'),
		fullScreen: asset('images/posts/DUHLESS2/fullscreen.jpg'),
	},
	{
		id: 'TIZER-BATORI',
		title: 'ТИЗЕР БАТОРИ',
		src: asset('images/posts/TIZER-BATORI/src.jpg'),
		'data-high-res': asset('images/posts/TIZER-BATORI/data-high-res.jpg'),
		'data-4x': asset('images/posts/TIZER-BATORI/data-4x.jpg'),
		fullScreen: asset('images/posts/TIZER-BATORI/fullscreen.jpg'),
	},
	{
		id: 'SOLNECNYI-UDAR',
		title: 'СОЛНЕЧНЫЙ УДАР',
		src: asset('images/posts/SOLNECNYI-UDAR/src.jpg'),
		'data-high-res': asset('images/posts/SOLNECNYI-UDAR/data-high-res.jpg'),
		'data-4x': asset('images/posts/SOLNECNYI-UDAR/data-4x.jpg'),
		fullScreen: asset('images/posts/SOLNECNYI-UDAR/fullscreen.jpg'),
	},
	{
		id: 'the-champions',
		title: 'the champions',
		src: asset('images/posts/the-champions/src.jpg'),
		'data-high-res': asset('images/posts/the-champions/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/the-champions/fullscreen.jpg'),
	},
	{
		id: 'the-champions-1',
		title: 'the champions',
		src: asset('images/posts/the-champions-1/src.jpg'),
		'data-high-res': asset('images/posts/the-champions-1/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/the-champions-1/fullscreen.jpg'),
	},
	{
		id: '22-MINUTY-1',
		title: '22 МИНУТЫ',
		src: asset('images/posts/22-MINUTY-1/src.jpg'),
		'data-high-res': asset('images/posts/22-MINUTY-1/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/22-MINUTY-1/fullscreen.jpg'),
	},
	{
		id: 'LEGENDA-17',
		title: 'ЛЕГЕНДА № 17',
		src: asset('images/posts/LEGENDA-17/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/LEGENDA-17/fullscreen.jpg'),
	},
	{
		id: 'SPION',
		title: '',
		src: asset('images/posts/SPION/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/SPION/fullscreen.png'),
	},
	{
		id: 'HAYTARMA',
		title: 'HAYTARMA',
		src: asset('images/posts/HAYTARMA/src.jpg'),
		'data-high-res': asset('images/posts/HAYTARMA/data-high-res.jpg'),
		'data-4x': asset('images/posts/HAYTARMA/data-4x.jpg'),
		fullScreen: asset('images/posts/HAYTARMA/fullscreen.jpg'),
	},
	{
		id: 'AMERICAN-HEIST-concept-2',
		title: 'AMERICAN HEIST  concept 2',
		src: asset('images/posts/AMERICAN-HEIST-concept-2/src.jpg'),
		'data-high-res': asset('images/posts/AMERICAN-HEIST-concept-2/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/AMERICAN-HEIST-concept-2/fullscreen.jpg'),
	},
	{
		id: 'AMERICAN-HEIST-1',
		title: 'AMERICAN HEIST',
		src: asset('images/posts/AMERICAN-HEIST-1/src.jpg'),
		'data-high-res': asset('images/posts/AMERICAN-HEIST-1/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/AMERICAN-HEIST-1/fullscreen.jpg'),
	},
	{
		id: 'AMERICAN-HEIST-2',
		title: 'AMERICAN HEIST',
		src: asset('images/posts/AMERICAN-HEIST-2/src.jpg'),
		'data-high-res': asset('images/posts/AMERICAN-HEIST-2/data-high-res.jpg'),
		'data-4x': asset('images/posts/AMERICAN-HEIST-2/data-4x.jpg'),
		fullScreen: asset('images/posts/AMERICAN-HEIST-2/fullscreen.jpg'),
	},
	{
		id: 'TIZER-1_VYPUSKNOI',
		title: 'ТИЗЕР#1_ВЫПУСКНОЙ',
		src: asset('images/posts/TIZER-1_VYPUSKNOI/src.jpg'),
		'data-high-res': asset('images/posts/TIZER-1_VYPUSKNOI/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/TIZER-1_VYPUSKNOI/fullscreen.jpg'),
	},
	{
		id: 'VOS-MERKA',
		title: 'ВОСЬМЕРКА',
		src: asset('images/posts/VOS-MERKA/src.jpg'),
		'data-high-res': asset('images/posts/VOS-MERKA/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/VOS-MERKA/fullscreen.jpg'),
	},
	{
		id: 'LEGENDA-17-KONTEPT-4',
		title: 'ЛЕГЕНДА №17 [концепт № 4]',
		src: asset('images/posts/LEGENDA-17-KONTEPT-4/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/LEGENDA-17-KONTEPT-4/fullscreen.jpg'),
	},
	{
		id: 'CONCEPT',
		title: 'CONCEPT',
		src: asset('images/posts/CONCEPT/src.jpg'),
		'data-high-res': asset('images/posts/CONCEPT/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/CONCEPT/fullscreen.jpg'),
	},
	{
		id: 'DUBROVSKII',
		title: 'ДУБРОВСКИЙ',
		src: asset('images/posts/DUBROVSKII/src.jpg'),
		'data-high-res': asset('images/posts/DUBROVSKII/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/DUBROVSKII/fullscreen.jpg'),
	},
	{
		id: 'the-meeting_CONCEPT_unofficial-version',
		title: 'the meeting_CONCEPT_unofficial version',
		src: asset('images/posts/the-meeting_CONCEPT_unofficial-version/src.jpg'),
		'data-high-res': asset(
			'images/posts/the-meeting_CONCEPT_unofficial-version/data-high-res.jpg'
		),
		'data-4x': null,
		fullScreen: asset(
			'images/posts/the-meeting_CONCEPT_unofficial-version/fullscreen.jpg'
		),
	},
	{
		id: 'LIVING-2',
		title: '',
		src: asset('images/posts/LIVING-2/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/LIVING-2/fullscreen.jpg'),
	},
	{
		id: 'AMERICAN-HEIST',
		title: 'AMERICAN HEIST',
		src: asset('images/posts/AMERICAN-HEIST/src.jpg'),
		'data-high-res': asset('images/posts/AMERICAN-HEIST/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/AMERICAN-HEIST/fullscreen.jpg'),
	},
	{
		id: 'TEMNYI-MIR-RAVNOVESIE-3',
		title: 'ТЕМНЫЙ МИР:РАВНОВЕСИЕ',
		src: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-3/src.jpg'),
		'data-high-res': asset('images/posts/TEMNYI-MIR-RAVNOVESIE-3/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-3/fullscreen.jpg'),
	},
	{
		id: 'TEMNYI-MIR-RAVNOVESIE-4',
		title: 'ТЕМНЫЙ МИР:РАВНОВЕСИЕ',
		src: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-4/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-4/fullscreen.jpg'),
	},
	{
		id: 'TEMNYI-MIR-RAVNOVESIE-5',
		title: 'ТЕМНЫЙ МИР:РАВНОВЕСИЕ',
		src: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-5/src.jpg'),
		'data-high-res': asset('images/posts/TEMNYI-MIR-RAVNOVESIE-5/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-5/fullscreen.jpg'),
	},
	{
		id: '22-MINUTY',
		title: '22 МИНУТЫ',
		src: asset('images/posts/22-MINUTY/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/22-MINUTY/fullscreen.jpg'),
	},
	{
		id: 'PODDUBNYI',
		title: 'ПОДДУБНЫЙ',
		src: asset('images/posts/PODDUBNYI/src.jpg'),
		'data-high-res': asset('images/posts/PODDUBNYI/data-high-res.jpg'),
		'data-4x': asset('images/posts/PODDUBNYI/data-4x.jpg'),
		fullScreen: asset('images/posts/PODDUBNYI/fullscreen.jpg'),
	},
	{
		id: 'concept_teaser-GFIS',
		title: 'concept_teaser+GFIS',
		src: asset('images/posts/concept_teaser-GFIS/src.jpg'),
		'data-high-res': asset('images/posts/concept_teaser-GFIS/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/concept_teaser-GFIS/fullscreen.jpg'),
	},
	{
		id: '18-12-ULANSKAY-BALLADA',
		title: '18 12: УЛАНСКАЯ БАЛЛАДА',
		src: asset('images/posts/18-12-ULANSKAY-BALLADA/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/18-12-ULANSKAY-BALLADA/fullscreen.jpg'),
	},
	{
		id: 'LIVING-1',
		title: 'LIVING',
		src: asset('images/posts/LIVING-1/src.jpg'),
		'data-high-res': asset('images/posts/LIVING-1/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/LIVING-1/fullscreen.jpg'),
	},
	{
		id: 'BATORI_TIZER',
		title: 'БАТОРИ_ТИЗЕР',
		src: asset('images/posts/BATORI_TIZER/src.jpg'),
		'data-high-res': asset('images/posts/BATORI_TIZER/data-high-res.jpg'),
		'data-4x': asset('images/posts/BATORI_TIZER/data-4x.jpg'),
		fullScreen: asset('images/posts/BATORI_TIZER/fullscreen.jpg'),
	},
	{
		id: 'BYSTREE-CEM-KROLIKI',
		title: 'БЫСТРЕЕ, ЧЕМ КРОЛИКИ',
		src: asset('images/posts/BYSTREE-CEM-KROLIKI/src.jpg'),
		'data-high-res': asset('images/posts/BYSTREE-CEM-KROLIKI/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/BYSTREE-CEM-KROLIKI/fullscreen.jpg'),
	},
	{
		id: 'ATOS-KP-TRI-MUSKETERA',
		title: 'АТОС ХП: ТРИ МУШКЕТЕРА',
		src: asset('images/posts/ATOS-KP-TRI-MUSKETERA/src.jpg'),
		'data-high-res': asset('images/posts/ATOS-KP-TRI-MUSKETERA/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/ATOS-KP-TRI-MUSKETERA/fullscreen.jpg'),
	},
	{
		id: 'D-ARTAN-YN-KP',
		title: 'д,Артаньян ХП',
		src: asset('images/posts/D-ARTAN-YN-KP/src.jpg'),
		'data-high-res': asset('images/posts/D-ARTAN-YN-KP/data-high-res.jpg'),
		'data-4x': null,
		fullScreen: asset('images/posts/D-ARTAN-YN-KP/fullscreen.jpg'),
	},
	{
		id: 'DOLGAY-SCASTLIVAY-ZIZN-1',
		title: 'ДОЛГАЯ СЧАСТЛИВАЯ ЖИЗНЬ',
		src: asset('images/posts/DOLGAY-SCASTLIVAY-ZIZN-1/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/DOLGAY-SCASTLIVAY-ZIZN-1/fullscreen.jpg'),
	},
	{
		id: 'DOLGAY-SCASTLIVAY-ZIZN',
		title: 'ДОЛГАЯ СЧАСТЛИВАЯ ЖИЗНЬ',
		src: asset('images/posts/DOLGAY-SCASTLIVAY-ZIZN/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/DOLGAY-SCASTLIVAY-ZIZN/fullscreen.jpg'),
	},
	{
		id: 'HOME-teaser',
		title: '',
		src: asset('images/posts/HOME-teaser/src.png'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/HOME-teaser/fullscreen.png'),
	},
	{
		id: 'THE-SPY-concept',
		title: 'THE SPY (concept)',
		src: asset('images/posts/THE-SPY-concept/src.png'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/THE-SPY-concept/fullscreen.png'),
	},
	{
		id: 'TEMNYI-MIR-RAVNOVESIE-2',
		title: 'ТЕМНЫЙ МИР:РАВНОВЕСИЕ',
		src: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-2/src.jpg'),
		'data-high-res': null,
		'data-4x': null,
		fullScreen: asset('images/posts/TEMNYI-MIR-RAVNOVESIE-2/fullscreen.jpg'),
	},
];